applications:
    starshot:

        # build:
        #     flavor: composer
        # type: "php:8.2"
        # dependencies:
        #     php:
        #         composer/composer: '^2.1'
        # runtime:
        #     extensions:
        #         - redis
        #         - sodium
        #         - apcu
        #         - blackfire

        stack:
            - "php@8.3":
                extensions:
                  - redis
                  - sodium
                  - apcu
                  - blackfire
            - "php83Packages.composer"

        relationships:
            database: 
                service: db 
            redis: 
                service: cache

        hooks:
            build: |
                set -eux
                composer --no-ansi --no-interaction install --no-progress --prefer-dist --optimize-autoloader
            deploy: |
                set -eux
                php ./drush/generate_drush_yml.php
                cd web
                bash $PLATFORM_APP_DIR/drush/deploy_drupal.sh

        mounts:
            '/web/sites/default/files':
                source: storage
                source_path: 'files'
            '/tmp':
                source: storage
                source_path: 'tmp'
            '/private':
                source: storage
                source_path: 'private'
            '/.drush':
                source: storage
                source_path: 'drush'
            '/drush-backups':
                source: storage
                source_path: 'drush-backups'
            '/.console':
                source: storage
                source_path: 'console'

        web:
            locations:
                '/':
                    root: 'web'
                    expires: 5m
                    passthru: '/index.php'
                    allow: false
                    rules:
                        '\.(avif|webp|jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
                            allow: true
                        '^/robots\.txt$':
                            allow: true
                        '^/sitemap\.xml$':
                            allow: true
                        '^/sites/sites\.php$':
                            scripts: false
                        '^/sites/[^/]+/settings.*?\.php$':
                            scripts: false
                '/sites/default/files':
                    allow: true
                    expires: 5m
                    passthru: '/index.php'
                    root: 'web/sites/default/files'
                    scripts: false
                    rules:
                        '^/sites/default/files/(css|js)':
                            expires: 2w

        crons:
            drupal:
                spec: '*/19 * * * *'
                commands: 
                    start: 'cd web ; drush core-cron'

services:
    db:
        type: mariadb:11.2

    cache:
        type: redis:7.2

routes:
    "https://{default}/":
        type: upstream
        upstream: "starshot:http"
        cache:
            enabled: true
            cookies: ['/^SS?ESS/', '/^Drupal.visitor/']

    "https://www.{default}/":
        type: redirect
        to: "https://{default}/"
